name: Firefly III
version: 0.0.6
slug: fireflyiii
description: A free and open source personal finance manager
url: https://github.com/aveseli/addon-firefly-iii/
homeassistant: 2021.3.0
webui: "[PROTO:ssl]://[HOST]:[PORT:80]"
services:
    - mysql:need
startup: "application"
arch:
    - amd64
    - armv7
boot: "auto"
hassio_api: true
hassio_role: "default"
map:
    - ssl
    - share:rw
    - config:rw
ports:
    80/tcp: 3473
ports_description:
    80/tcp: "Web interface"
options:
    ssl: false
    certfile: "fullchain.pem"
    keyfile: "privkey.pem"
schema:
    log_level: "list(trace|debug|info|notice|warning|error|fatal)?"
    certfile: "str"
    keyfile: "str"
    ssl: "bool"
    mapbox_api_key: "str?"
image: "ghcr.io/aveseli/firefly-iii/{arch}"
